# Implementation of Simple ML Mode

In [43]:
import sklearn.datasets     #Dataset taken from sklearn.datset libary
import numpy as np

In [44]:
#from dataset we took breast_cancer dataset and assign  as cancer_ds
cancer_ds=sklearn.datasets.load_breast_cancer() 

In [45]:
#divide dataset into two form data and target and asign them x and y respectively
x = cancer_ds.data          
y = cancer_ds.target

In [47]:
print(x)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [48]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [49]:
print(x.shape, y.shape)  
#shape function is use for determine no. of rows and coloumn ( x has 569 rows, 30 coloumn and y has 569 rowsm 1 coloumn)

(569, 30) (569,)


In [6]:
#get dataset inside dataframe
import pandas as pd
data = pd.DataFrame(cancer_ds.data, columns = cancer_ds.feature_names) 
#put the dataset into dataframe using panda libary

In [7]:
data['class'] = cancer_ds.target         
#rename target feature to class feature

In [8]:
data.head()    
#this function is use to print first five datapoint from dataset

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [9]:
print(data['class'].value_counts())        
#value_counts function use to get No of distinct datapoint in features

1    357
0    212
Name: class, dtype: int64


In [67]:
print(cancer_ds.target_names)         

['malignant' 'benign']


In [68]:
data.groupby('class').mean() 
#group function is returns a tuple containing all the subgroups of the match
#mean function is used to calculate mean

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

# Train Test Split

In [12]:
from sklearn.model_selection import train_test_split
#to split dataset into train and test we use train_test_split function

In [70]:
x = data.drop('class', axis=1)
y = data['class']

In [74]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify = y, random_state= 1)

#80% data used for training purpose and 20% data used for testing purpose
#stratify retain the same proportion of classes in the train and test sets 
# random_state is used to  avoid getting different values for train and test every time execution

In [71]:
print(y.shape, y_train.shape, y_test.shape)
# No 0f rows and coloumn in train and test data set

(569,) (398,) (171,)


In [16]:
print(x.shape, x_train.shape, x_test.shape)
# No 0f rows and coloumn in train and test data set

(569, 30) (171, 30) (398, 30)


In [72]:
print(y.mean, y_test.mean, y_train.mean)
#calculating test and train dataset mean

<bound method Series.mean of 0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: class, Length: 569, dtype: int32> <bound method Series.mean of 40     0
330    0
146    0
548    1
95     0
      ..
324    1
218    0
474    1
423    1
60     1
Name: class, Length: 171, dtype: int32> <bound method Series.mean of 387    1
94     0
565    0
385    0
230    0
      ..
114    1
242    1
17     0
41     0
198    0
Name: class, Length: 398, dtype: int32>


In [73]:
print(x.mean, x_test.mean, x_train.mean)

<bound method DataFrame.mean of      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean con

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify = y, random_state= 1)
print(x.mean, x_test.mean, x_train.mean)
# output when 70% dataset used for training and 30% used for testing

<bound method DataFrame.mean of      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean con

In [75]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify = y)
print(x.mean, x_test.mean, x_train.mean)
#output when random state not used

<bound method DataFrame.mean of      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean con

In [21]:
data.describe()
# describe() is used to view some basic statistical details like percentile, mean, std

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [80]:
x_binarised_train =x_train.apply(pd.cut, bins=2, labels=[1,0])
x_binarised_test =x_test.apply(pd.cut, bins=2, labels=[1,0])
#this function is used to convert continuous variable to a categorical variable
type(x_binarised_train)
#type returns class type of the argument(object) passed as parameter

pandas.core.frame.DataFrame

In [86]:
x_binarised_train = x_binarised_train .values
x_binarised_test =x_binarised_test.values
type(x_binarised_train)
#values is used  to get a Numpy representation of the DataFrame

numpy.ndarray

In [87]:
print(x_binarised_train.shape[1])
#No odf 1s in x_binarised_train dataset

30


In [104]:
#b =10

#from random import randint

#i = randint(0, x_binarised_train.shape[0])

#To get optimal value b we calculate accuracy and accurate_row of each valueof b (0-30)
#if we not extra one the it take upto 29 so we take extra one
for b in range (x_binarised_train.shape[1]+1):

    accurate_rows =0

    for x,y in zip(x_binarised_train, y_train):
        y_pred = (np.sum(x)>=b)
        accurate_rows += (y == y_pred)
    
    print(b, accurate_rows,accurate_rows/x_binarised_train.shape[0])


    
#from obsevation for b=27 has highest accuracy
    

0 250 0.628140703517588
1 250 0.628140703517588
2 250 0.628140703517588
3 250 0.628140703517588
4 250 0.628140703517588
5 250 0.628140703517588
6 250 0.628140703517588
7 250 0.628140703517588
8 250 0.628140703517588
9 250 0.628140703517588
10 250 0.628140703517588
11 250 0.628140703517588
12 250 0.628140703517588
13 252 0.6331658291457286
14 254 0.6381909547738693
15 254 0.6381909547738693
16 255 0.6407035175879398
17 259 0.6507537688442211
18 262 0.6582914572864321
19 264 0.6633165829145728
20 276 0.6934673366834171
21 284 0.7135678391959799
22 293 0.7361809045226131
23 308 0.7738693467336684
24 320 0.8040201005025126
25 329 0.8266331658291457
26 341 0.8567839195979899
27 351 0.8819095477386935
28 346 0.8693467336683417
29 322 0.8090452261306532
30 289 0.7261306532663316


In [106]:
if(np.sum(x_binarised_train[ i, :] >=b)):
   print("Model prediction is malignant")
else:
   print("Model prediction is benign")

if(y_train[i]==0):
   print("Model outcome is malignant")
else:
   print("Model outcome is benign")
   

Model prediction is benign
Model outcome is benign


In [103]:
from sklearn.metrics import classification_report, confusion_matrix
b=27

accurate_rows =0

for x,y in zip(x_binarised_test, y_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows += (y == y_pred)
    
print( b, accurate_rows,accurate_rows/x_binarised_test.shape[0])


b=28

accurate_rows =0

for x,y in zip(x_binarised_test, y_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows += (y == y_pred)
    
print(b, accurate_rows,accurate_rows/x_binarised_test.shape[0])

#from accuracy and accurate_rows b=27 is optimal


27 143 0.8362573099415205
28 138 0.8070175438596491


In [113]:
from sklearn import metrics
Sum= np.sum(x_binarised_test, axis=1)   #Summation of x(i) values for all features
y_pred =  (Sum>= 28)
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print("confusion Matrix\n", confusion_matrix)

confusion Matrix
 [[52 12]
 [21 86]]


# Conclusion

In [ ]:
#During trainig we got optimal  value of b is 27 with accuracy 0.88
#During testing we got optimal  valueof b  is 27 with accuracy 0.83
#so It is conclude that this modal with b=27 has the highest Accuracy.
#From confusion Matrix 52 rows correctly predicted as malignant and 86 rows correctly predicted as benign
#12 rows incorrectly predicated as benign and 21 rows incorrectly predicated as malignant .